name: clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.1.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.1.1
  http: ^1.6.0
  internet_connection_checker: ^3.0.1
  shared_preferences: ^2.5.3
user_repository:
 path: packages\user_repository\lib\user_repository.dart
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
